# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: Print out the list of available commands
    cmds:
      - task -l
    silent: true
  run:
    desc: Run application
    cmds:
      - go run ./main.go {{.CLI_ARGS}}
  generate:types:
    desc: Generate string types for enums using stringer
    cmds:
      - $HOME/go/bin/stringer --type TokenType ./lexer
