// Code generated by "stringer --type TokenType ./lexer"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LEFT_CURLY-0]
	_ = x[RIGHT_CURLY-1]
	_ = x[LEFT_BRACKET-2]
	_ = x[RIGHT_BRACKET-3]
	_ = x[COMMA-4]
	_ = x[DOT-5]
	_ = x[MINUS-6]
	_ = x[PLUS-7]
	_ = x[SEMICOLON-8]
	_ = x[SLASH-9]
	_ = x[STAR-10]
	_ = x[PERCENT-11]
	_ = x[BANG-12]
	_ = x[BANG_EQUAL-13]
	_ = x[EQUAL-14]
	_ = x[EQUAL_EQUAL-15]
	_ = x[GREATER-16]
	_ = x[GREATER_EQUAL-17]
	_ = x[LESS-18]
	_ = x[LESS_EQUAL-19]
	_ = x[IDENTIFIER-20]
	_ = x[STRING-21]
	_ = x[NUMBER-22]
	_ = x[VAR-23]
	_ = x[AND-24]
	_ = x[OR-25]
	_ = x[TRUE-26]
	_ = x[FALSE-27]
	_ = x[NULL-28]
	_ = x[IF-29]
	_ = x[ELSE-30]
	_ = x[FOR-31]
	_ = x[WHILE-32]
	_ = x[FUNCTION-33]
	_ = x[RETURN-34]
	_ = x[CLASS-35]
	_ = x[THIS-36]
	_ = x[SUPER-37]
	_ = x[PRINT-38]
	_ = x[EOF-39]
}

const _TokenType_name = "LEFT_CURLYRIGHT_CURLYLEFT_BRACKETRIGHT_BRACKETCOMMADOTMINUSPLUSSEMICOLONSLASHSTARPERCENTBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALIDENTIFIERSTRINGNUMBERVARANDORTRUEFALSENULLIFELSEFORWHILEFUNCTIONRETURNCLASSTHISSUPERPRINTEOF"

var _TokenType_index = [...]uint8{0, 10, 21, 33, 46, 51, 54, 59, 63, 72, 77, 81, 88, 92, 102, 107, 118, 125, 138, 142, 152, 162, 168, 174, 177, 180, 182, 186, 191, 195, 197, 201, 204, 209, 217, 223, 228, 232, 237, 242, 245}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
